# Generated by Django 5.0.7 on 2024-07-20 10:15

import accounts.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.DateField(default=datetime.date(2000, 1, 1))),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path)),
                ('nickname', models.CharField(default='User', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
