# Generated by Django 5.0.6 on 2024-07-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_program_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='content',
        ),
        migrations.AddField(
            model_name='program',
            name='center_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='directions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='event_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='event_period',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='participants',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='registration_period',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='session_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
