# Generated by Django 5.0.6 on 2024-07-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_remove_program_content_program_center_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='directions',
        ),
    ]
