# Generated by Django 5.0.6 on 2024-07-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_remove_program_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='application_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
