# Generated by Django 5.0.6 on 2024-07-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_remove_policy_application_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benefit',
            name='application_period',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benefit',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
    ]
