# Generated by Django 5.0.6 on 2024-07-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_policy_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scrap',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scrap',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='program.program'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='program.policy'),
        ),
    ]
