# Generated by Django 5.0.1 on 2024-07-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_alter_scrap_unique_together_scrap_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='policy_images/'),
        ),
    ]
