# Generated by Django 5.0.3 on 2024-07-04 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('intro', models.TextField()),
                ('content_1', models.CharField(max_length=150)),
                ('content_2', models.CharField(blank=True, max_length=150, null=True)),
                ('content_3', models.CharField(blank=True, max_length=150, null=True)),
                ('content_4', models.CharField(blank=True, max_length=150, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('nickname', models.CharField(max_length=100)),
                ('tag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.TextField(blank=True, null=True)),
                ('advice', models.TextField(blank=True, null=True)),
                ('pledge', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('mento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mentoring.mento')),
            ],
        ),
    ]
