# Generated by Django 5.0.3 on 2024-07-03 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mentoring.mento'),
            preserve_default=False,
        ),
    ]
