# Generated by Django 5.0.6 on 2024-07-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_comment'),
        ('mentoring', '0003_question_mento'),
    ]

    operations = [
    ]
